---
- hosts: jenkins-windows-nodes
  tasks:
  
    - name: Download jdk-8u211-windows-x64.exe
      win_get_url:
        url: 'http://52.63.197.165:8081/artifactory/installers/jdk-8u211-windows-x64.exe'
        dest: C:\Installers\jdk-8u211-windows-x64.exe
        url_username: admin
        url_password: password
  
    - name: Install oracle java
      win_package:
        product_id: '{26A24AE4-039D-4CA4-87B4-2F64180211F0}'
        arguments: /s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature"
        path: C:\Installers\jdk-8u211-windows-x64.exe
        state: present

    - name: Install chrome
      win_package:
        product_id: 'Google Chrome'
        arguments: /silent /install
        path: C:\Installers\ChromeStandaloneSetup64.exe
        state: present

