---
- hosts: jenkins-windows-nodes
  tasks: []
  
- hosts: jenkins-windows-nodes
  serial: 1
  
  #pre_tasks:
  #- name: stop jenkins service
  #  win_service: 
  #    name: jenkinsslave-C__temp
  #    state: stopped
    
  roles:
  - java
  - chrome
  
  #post_tasks:
  #- name: start jenkins service
  #  win_service: 
  #    name: jenkinsslave-C__temp
  #    state: started

