---
- hosts: jenkins-windows-nodes
  tasks: []
  
  pre_tasks:
  - name: stop jenkins service
    win_service: 
      name: jenkinsslave-C__temp
      state: stopped
    
  roles:
  - java
  
  post_tasks:
  - name: start jenkins service
    win_service: 
      name: jenkinsslave-C__temp
      state: started

