---
- name: Download "{{ jdk_installer }}"
  get_url:
    url: 'http://13.238.201.132:8081/artifactory/installers/{{ jdk_installer }}'
    dest: "C:\Installers\{{ jdk_installer }}"

- name: Install oracle java
  win_package:
    product_id: '{64A3A4F4-B792-11D6-A78A-00B0D0180231}'
    arguments: /s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature"
    path: C:\Installers\jdk-8u231-windows-x64.exe
    state: present

- name: Set Java_home
  win_environment:
    state: present
    name: JAVA_HOME
    value: 'C:\program files\java\jdk1.{{ java_major_version }}_{{ java_minor_version }}'
    level: machine

- name: Add Java to path
  win_path:
    elements:
      - 'c:\program files\java\jdk{{ java_major_version }}_{{ java_minor_version }}\bin'
