---  
- name: Download "{{ jdk_installer }}"
  win_get_url:
    url: '{{ artifactory }}/installers/java/{{ jdk_installer }}'
    dest: '{{ installer_dir }}\{{ jdk_installer }}'
    url_username: admin # temp for now will use vault.
    url_password: password
    force: no

- name: Create a file from a Jinja2 template
  win_template:
    src: uninstall_existing_java.bat.j2
    dest: C:\Installers\uninstall_existing_java.bat
    
- name: uninstall existing Oracle java
  win_command: C:\Installers\uninstall_existing_java.bat
  
- name: Install oracle java
  win_package:
    product_id: '{{ uninstall_prod_id }}'
    arguments: /s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature"
    path: '{{ installer_dir }}\{{ jdk_installer }}'
    state: present

- name: Set Java_home
  win_environment:
    state: present
    name: JAVA_HOME
    value: 'C:\program files\java\jdk1.{{ java_major_version }}_{{ java_minor_version }}'
    level: machine

- name: Add Java to path
  win_path:
    elements:
      - 'c:\program files\java\jdk{{ java_major_version }}_{{ java_minor_version }}\bin'
