---  
- name: Download "{{ jdk_installer }}"
  win_get_url:
    url: '{{ artifactory }}/installers/java/{{ jdk_installer }}'
    dest: C:\Installers\{{ jdk_installer }}
    url_username: admin
    url_password: password
    force: no

- name: Install oracle java
  win_package:
    product_id: '{{ uninstall_prod_id }}'
    arguments: /s ADDLOCAL="ToolsFeature,SourceFeature,PublicjreFeature"
    path: C:\Installers\{{ jdk_installer }}
    state: present

- name: Set Java_home
  win_environment:
    state: present
    name: JAVA_HOME
    value: 'C:\program files\java\jdk1.{{ java_major_version }}_{{ java_minor_version }}'
    level: machine

- name: Add Java to path
  win_path:
    elements:
      - 'c:\program files\java\jdk{{ java_major_version }}_{{ java_minor_version }}\bin'
